<?

/**********************************************************

**********# Name          : Shambhu Prasad Patnaik #*******

**********# Company       : Aynsoft Pvt. Ltd.   #**********

**********# Copyright (c) www.aynsoft.com 2005  #**********

**********************************************************/

//define("PATH_TO_MAIN","");

define("PATH_TO_MAIN","");

define("PATH_TO_ADMIN","my_admin/");

define("PATH_TO_TEMPLATE","template/template1/");

define("PATH_TO_IMAGE","image/");

define("PATH_TO_IMG","img/");

define("PATH_TO_LANGUAGE","language/");

define("PATH_TO_BOX","box/");

define("PATH_TO_CLASS","class/");

define("PATH_TO_APPLY_RESUME","apply_resume/");

define("PATH_TO_APPLY_RESUME_NOLOGIN","apply_resumenl/");

define("PATH_TO_EMAIL_ATTACHMENT","mail_attachment/");

define("PATH_TO_RECRUITER_EMAIL_ATTACHMENT","recruiter_mail_attachment/");

define("PATH_TO_TEMP","temp/");

define("PATH_TO_NEWSLETTER_HISTORY","newsletter_history/");

define("PATH_TO_BACKUP","backup/");

define("PATH_TO_SITE_BACKUP","site_backup/");

define("PATH_TO_EXCEL","excel/");

define("PATH_TO_NEWSLETTERS","newsletters/");

define("PATH_TO_RESUME","resume/");

define("PATH_TO_PHOTO","photo/");

define("PATH_TO_LOGO","logo/");

define("PATH_TO_BANNER","banner/");

define("PATH_TO_ARTICLE_PHOTO","article_image/");

define("PATH_TO_COURSE_PHOTO","course_pic/");

define("PATH_TO_THEMES","themes/");

define("PATH_TO_FORUM","forum/");

define("PATH_TO_FORUM_IMAGE","forum_image/");

define("PATH_TO_MOBILE","mobile/");

define("PATH_TO_JOBFAIR_LOGO","jobfair/logo/");

define("PATH_TO_SLIDER_IMAGE","image/slider/");



define("PATH_TO_MODULE","modules/");

define("PATH_TO_DOWNLOAD_RESUME","download_resume/");

define("PATH_TO_AJAX","ajax/");

define("PATH_TO_CRON_JOB","cron_job/");



//define("HOST_NAME_MAIN",$_SERVER["REQUEST_SCHEME"]."://".$_SERVER["HTTP_HOST"]);

//define("HOST_NAME",$_SERVER["REQUEST_SCHEME"]."://".$_SERVER["HTTP_HOST"]."/".PATH_TO_MAIN);

define("HOST_NAME_MAIN","https://".$_SERVER["HTTP_HOST"]);

define("HOST_NAME","https://".$_SERVER["HTTP_HOST"]."/".PATH_TO_MAIN);

define('PATH_TO_MAIN_PHYSICAL',$_SERVER['DOCUMENT_ROOT']."/".PATH_TO_MAIN);



define('PATH_TO_MAIN_PHYSICAL_LANGUAGE',PATH_TO_MAIN_PHYSICAL.PATH_TO_LANGUAGE);

define('PATH_TO_MAIN_PHYSICAL_APPLY_RESUME',PATH_TO_MAIN_PHYSICAL.PATH_TO_APPLY_RESUME);

define('PATH_TO_MAIN_PHYSICAL_APPLY_NOLOGIN_RESUME',PATH_TO_MAIN_PHYSICAL.PATH_TO_APPLY_RESUME_NOLOGIN);

define('PATH_TO_MAIN_PHYSICAL_EMAIL_ATTACHMENT',PATH_TO_MAIN_PHYSICAL.PATH_TO_EMAIL_ATTACHMENT);

define('PATH_TO_MAIN_PHYSICAL_TEMP',PATH_TO_MAIN_PHYSICAL.PATH_TO_TEMP);

define('PATH_TO_MAIN_PHYSICAL_RECRUITER_EMAIL_ATTACHMENT',PATH_TO_MAIN_PHYSICAL.PATH_TO_RECRUITER_EMAIL_ATTACHMENT);

define('PATH_TO_MAIN_PHYSICAL_NEWSLETTER_HISTORY',PATH_TO_MAIN_PHYSICAL.PATH_TO_NEWSLETTER_HISTORY);



define('PATH_TO_MAIN_PHYSICAL_ARTICLE_PHOTO',PATH_TO_MAIN_PHYSICAL.PATH_TO_ARTICLE_PHOTO);

define('PATH_TO_MAIN_PHYSICAL_COURSE_PHOTO',PATH_TO_MAIN_PHYSICAL.PATH_TO_COURSE_PHOTO);

define('PATH_TO_MAIN_PHYSICAL_RESUME',PATH_TO_MAIN_PHYSICAL.PATH_TO_RESUME);

define('PATH_TO_MAIN_PHYSICAL_JOBFAIR_LOGO',PATH_TO_MAIN_PHYSICAL.PATH_TO_JOBFAIR_LOGO);

define('PATH_TO_MAIN_PHYSICAL_PHOTO',PATH_TO_MAIN_PHYSICAL.PATH_TO_PHOTO);

define('PATH_TO_MAIN_PHYSICAL_BANNER',PATH_TO_MAIN_PHYSICAL.PATH_TO_BANNER);

define('PATH_TO_MAIN_PHYSICAL_LOGO',PATH_TO_MAIN_PHYSICAL.PATH_TO_LOGO);

define('PATH_TO_MAIN_PHYSICAL_MODULE',PATH_TO_MAIN_PHYSICAL.PATH_TO_MODULE);

define('PATH_TO_MAIN_ADMIN_PHYSICAL_LANGUAGE',PATH_TO_MAIN_PHYSICAL.PATH_TO_ADMIN.PATH_TO_LANGUAGE);

define('PATH_TO_MAIN_PHYSICAL_DOWNLOAD_RESUME',PATH_TO_MAIN_PHYSICAL.PATH_TO_DOWNLOAD_RESUME);



define('PATH_TO_MAIN_PHYSICAL_BOX',PATH_TO_MAIN_PHYSICAL.PATH_TO_BOX);

define('PATH_TO_MAIN_PHYSICAL_CLASS',PATH_TO_MAIN_PHYSICAL.PATH_TO_CLASS);

define('PATH_TO_MAIN_PHYSICAL_BACKUP',PATH_TO_MAIN_PHYSICAL.PATH_TO_ADMIN.PATH_TO_BACKUP);

define('PATH_TO_MAIN_PHYSICAL_SITE_BACKUP',PATH_TO_MAIN_PHYSICAL.PATH_TO_ADMIN.PATH_TO_SITE_BACKUP);

define('PATH_TO_MAIN_PHYSICAL_EXCEL',PATH_TO_MAIN_PHYSICAL.PATH_TO_ADMIN.PATH_TO_EXCEL);

define('PATH_TO_MAIN_PHYSICAL_NEWSLETTERS',PATH_TO_MAIN_PHYSICAL.PATH_TO_ADMIN.PATH_TO_NEWSLETTERS);

define('PATH_TO_MAIN_PHYSICAL_THEMES',PATH_TO_MAIN_PHYSICAL.PATH_TO_THEMES);

define('PATH_TO_MAIN_PHYSICAL_SLIDER_IMAGE',PATH_TO_MAIN_PHYSICAL.PATH_TO_IMAGE.'slider/');



/////froum////

define('PATH_TO_MAIN_FORUM_PHYSICAL_LANGUAGE',PATH_TO_MAIN_PHYSICAL.PATH_TO_FORUM.PATH_TO_LANGUAGE);

define("PATH_TO_MAIN_PHYSICAL_FORUM_IMAGE",PATH_TO_MAIN_PHYSICAL.PATH_TO_FORUM_IMAGE);

//tiny mce upload image dir//

define("PATH_TO_UPLOAD_IMAGE","uploads/images/");

define('PATH_TO_MAIN_PHYSICAL_UPLOAD_IMAGE',PATH_TO_MAIN_PHYSICAL.PATH_TO_UPLOAD_IMAGE);

ini_set('error_log',PATH_TO_MAIN_PHYSICAL.'test.log');

//////mobile/////

define('PATH_TO_MAIN_PHYSICAL_MOBILE',PATH_TO_MAIN_PHYSICAL.PATH_TO_MOBILE);

define('PATH_TO_MAIN_MOBILE_PHYSICAL_LANGUAGE',PATH_TO_MAIN_PHYSICAL.PATH_TO_MOBILE.PATH_TO_LANGUAGE);



//Quiz

define("PATH_TO_QUIZ","quiz/");

define('PATH_TO_MAIN_QUIZ_PHYSICAL_LANGUAGE',PATH_TO_MAIN_PHYSICAL.PATH_TO_QUIZ.PATH_TO_LANGUAGE);



//LMS

define("PATH_TO_LMS","lms/");

define('PATH_TO_MAIN_LMS_PHYSICAL_LANGUAGE',PATH_TO_MAIN_PHYSICAL.PATH_TO_LMS.PATH_TO_LANGUAGE);

define("PATH_TO_MAIN_PHYSICAL_LMS_THUMB_IMAGE",PATH_TO_MAIN_PHYSICAL.PATH_TO_UPLOAD_IMAGE);


// reports

define("PATH_TO_REPORTS","reports/");
define('PATH_TO_MAIN_REPORTS_PHYSICAL_LANGUAGE',PATH_TO_MAIN_PHYSICAL.PATH_TO_REPORTS.PATH_TO_LANGUAGE);

?>